# Generated by Django 6.0.3 on 2026-03-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
