# Generated by Django 6.0.3 on 2026-03-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_company_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='selected_at',
        ),
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('open', 'Відкритий'), ('closed', 'Закритий'), ('awarded', 'Призначений переможець')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='tender',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to='tenders.company'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='tender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_record', to='tenders.tender'),
        ),
    ]
