# Generated by Django 6.0.3 on 2026-03-27 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_remove_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='tender',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='deadline',
            field=models.DateField( default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winner',
            name='selected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('open', 'Відкритий'), ('awarded', 'Призначено')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
